apiVersion: v1
kind: Service
metadata:
  annotations:

  labels:
    app: nginx-ingress
  name: nginx-ingress-rc
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30001
  - name: http
    nodePort: 30002
    port: 80
    targetPort: 80
  selector:
    app: nginx-ingress
  type: LoadBalancer
